const questions = {//changing file path is boring, so I saved images in img folder and marged the same category in one folder.
    clothing: [
        { name: "Shirt", image: "./img/shirt.png" },
        { name: "Pants", image: "./img/pants.png" },
        { name: "Jacket", image: "./img/jacket.png" },
        { name: "Sweater", image: "./img/sweater.png" },
        { name: "Skirt", image: "./img/skirt.png" },
        { name: "Hat", image: "./img/hat.png" },
        { name: "Scarf", image: "./img/scarf.png" },
        { name: "Gloves", image: "./img/gloves.png" },
        { name: "Socks", image: "./img/socks.png" },
        { name: "Shoes", image: "./img/shoes.png" },
        { name: "Dress", image: "./img/dress.png" },
        { name: "Coat", image: "./img/coat.png" },
        { name: "T-shirt", image: "./img/tshirt.png" },
        { name: "Jeans", image: "./img/jeans.png" },
        { name: "Belt", image: "./img/belt.png" },
        { name: "Shorts", image: "./img/shorts.png" },
        { name: "Vest", image: "./img/vest.png" },
        { name: "Suit", image: "./img/suit.png" },
        { name: "Tie", image: "./img/tie.png" },
        { name: "Boots", image: "./img/boots.png" },
        { name: "Cap", image: "./img/cap.png" },
        { name: "Sandals", image: "./img/sandals.png" },
        { name: "Slippers", image: "./img/slippers.png" },
        { name: "Raincoat", image: "./img/raincoat.png" },
        { name: "Glasses", image: "./img/glasses.png" },
        { name: "Watch", image: "./img/watch.png" },
        { name: "Hoodie", image: "./img/hoodie.png" },
    ],
    food: [
        { name: "Apple", image: "./img/apple.png" },
        { name: "Banana", image: "./img/banana.png" },
        { name: "Orange", image: "./img/orange.png" },
        { name: "Strawberry", image: "./img/strawberry.png" },
        { name: "Grapes", image: "./img/grapes.png" },
        { name: "Watermelon", image: "./img/watermelon.png" },
        { name: "Pineapple", image: "./img/pineapple.png" },
        { name: "Mango", image: "./img/mango.png" },
        { name: "Blueberry", image: "./img/blueberry.png" },
        { name: "Cherry", image: "./img/cherry.png" },
        { name: "Tomato", image: "./img/tomato.png" },
        { name: "Potato", image: "./img/potato.png" },
        { name: "Carrot", image: "./img/carrot.png" },
        { name: "Cucumber", image: "./img/cucumber.png" },
        { name: "Pepper", image: "./img/pepper.png" },
        { name: "Onion", image: "./img/onion.png" },
        { name: "Broccoli", image: "./img/broccoli.png" },
        { name: "Cabbage", image: "./img/cabbage.png" },
        { name: "Lettuce", image: "./img/lettuce.png" },
        { name: "Rice", image: "./img/rice.png" },
        { name: "Bread", image: "./img/bread.png" },
        { name: "Pasta", image: "./img/pasta.png" },
        { name: "Cheese", image: "./img/cheese.png" },
        { name: "Egg", image: "./img/egg.png" },
        { name: "Chicken", image: "./img/chicken.png" },
        { name: "Fish", image: "./img/fish.png" },
        { name: "Meat", image: "./img/meat.png" },
        { name: "Pizza", image: "./img/pizza.png" },
        { name: "Cake", image: "./img/cake.png" },
        { name: "Ice Cream", image: "./img/icecream.png" }
    ],
    animal: [
        { name: "Dog", image: "./img/dog.png" },
        { name: "Cat", image: "./img/cat.png" },
        { name: "Horse", image: "./img/horse.png" },
        { name: "Cow", image: "./img/cow.png" },
        { name: "Sheep", image: "./img/sheep.png" },
        { name: "Goat", image: "./img/goat.png" },
        { name: "Pig", image: "./img/pig.png" },
        { name: "Rabbit", image: "./img/rabbit.png" },
        { name: "Deer", image: "./img/deer.png" },
        { name: "Bear", image: "./img/bear.png" },
        { name: "Fox", image: "./img/fox.png" },
        { name: "Wolf", image: "./img/wolf.png" },
        { name: "Tiger", image: "./img/tiger.png" },
        { name: "Lion", image: "./img/lion.png" },
        { name: "Elephant", image: "./img/elephant.png" },
        { name: "Giraffe", image: "./img/giraffe.png" },
        { name: "Monkey", image: "./img/monkey.png" },
        { name: "Kangaroo", image: "./img/kangaroo.png" },
        { name: "Panda", image: "./img/panda.png" },
        { name: "Koala", image: "./img/koala.png" },
        { name: "Penguin", image: "./img/penguin.png" },
        { name: "Seal", image: "./img/seal.png" },
        { name: "Whale", image: "./img/whale.png" },
        { name: "Shark", image: "./img/shark.png" },
        { name: "Dolphin", image: "./img/dolphin.png" },
        { name: "Frog", image: "./img/frog.png" },
        { name: "Snake", image: "./img/snake.png" },
        { name: "Turtle", image: "./img/turtle.png" },
        { name: "Crocodile", image: "./img/crocodile.png" }
    ]
};